version: "3"

services:
  ews-db:
    image: postgres:14
    volumes:
      - /var/lib/postgresql/ews-db-psql:/var/lib/postgresql/data
    ports:
      - 5555:5432
    environment:
      POSTGRES_DB: ews
      POSTGRES_PASSWORD: ews
      POSTGRES_USER: ews
    networks:
      - internal
  
  # ews-http-server:
  #   build: .
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - ews-db
  #   networks:
  #     - internal
  #   volumes:
  #     - ./.env:/app/.env
  #     - ./data/:/app/data/

networks:
  internal:
    driver: bridge